version: 1

disable_existing_loggers: True
formatters:
  simple:
    format: "%(asctime)s %(message)s"
    datefmt: "%H:%M:%S"
  extended:
    format: "%(asctime)s %(name)s %(levelname)s: %(message)s"

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: simple

loggers:
  __main__:
    level: INFO
    handlers: [console]
    propagate: False
